package consts

const TemplateGenCtrlControllerDefineAndNew = `
// =================================================================================
// This is auto-generated by Fine CLI tool only once. Fill this file as you wish.
// {CreatedAt}.
// =================================================================================

package {Package}

import (
	{ImportPath}
)

type {CtrlName} struct{}

func New() {InterfaceName} {
	return &{CtrlName}{}
}
`

const TemplateGenCtrlControllerMethodFunc = `
// =================================================================================
// This is auto-generated by Fine CLI tool only once. Fill this file as you wish.
// {CreatedAt}.
// =================================================================================

package {Version}

import (
	"github.com/gin-gonic/gin"

	"{ImportPath}"
)

//	@Summary	{Module}/{Version}/{MethodNameSnake}
//	@Tags		{Module}
//	@Accept		x-www-form-urlencoded
//	@Router		/{Module}/{Version}/{MethodNameSnake} [post]
//	@Param		{MethodNameSnake}		body	{Version}.{MethodName}Req	true	"form params"
//	@Success	200		{object}	f.JsonResult{data={Version}.{MethodName}Res}
func (c *{CtrlName}) {MethodName}(ctx *gin.Context, req *{Version}.{MethodName}Req) (res *{Version}.{MethodName}Res, err error) {
	return
}
`

const PatternCtrlDefinition = `func\s+\(.+?\)\s+\w+\(.+?\*(\w+)\.(\w+)Req\)\s+\(.+?\*(\w+)\.(\w+)Res,\s+\w+\s+error\)\s+{`

const TemplateGenCtrlApiInterface = `
// =================================================================================
// Code generated and maintained by Fine CLI tool. DO NOT EDIT.
// {CreatedAt}.
// =================================================================================

package {Module}

import (
{ImportPaths}
)

{Interfaces}
`

const TemplateGenCtrlSdkPkgNew = `
// =================================================================================
// This is auto-generated by Fine CLI tool only once. Fill this file as you wish.
// {CreatedAt}.
// =================================================================================

package {PkgName}

import "github.com/ZYallers/fine/contrib/sdk/httpclient"

type implementer struct {
	config httpclient.Config
}

func New(config httpclient.Config) IClient {
	return &implementer{config: config}
}
`

const TemplateGenCtrlSdkIClient = `
// =================================================================================
// Code generated and maintained by Fine CLI tool. DO NOT EDIT.
// {CreatedAt}.
// =================================================================================

package {PkgName}

import (
)

type IClient interface {
}
`

const TemplateGenCtrlSdkImplementer = `
// =================================================================================
// Code generated and maintained by Fine CLI tool. DO NOT EDIT.
// {CreatedAt}.
// =================================================================================

package {PkgName}

import (
	"github.com/gin-gonic/gin"
	"github.com/ZYallers/fine/contrib/sdk/httpclient"

{ImportPaths}
)

type implementer{ImplementerName} struct {
	*httpclient.Client
}

`

const TemplateGenCtrlSdkImplementerNew = `
func (i *implementer) {ImplementerName}() {Module}.I{ImplementerName} {
	return &implementer{ImplementerName}{httpclient.New(i.config)}
}

`

const TemplateGenCtrlSdkImplementerFunc = `
func (i *implementer{ImplementerName}) {MethodName}(ctx *gin.Context, req *{Version}.{MethodName}Req) (res *{Version}.{MethodName}Res, err error) {
	res = new({Version}.{MethodName}Res)
	err = i.Request(ctx, req, res)
	return
}
`
